version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
      - ./data/redis:/data/redis

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  cache:
